pipeline:
  npm_install:
    image: node:10.2.1
    commands:
      - env
      - yarn
  publish:
    image: plugins/docker
    username: josmo
    secrets: [ docker_password ]
    repo: josmo/node-sha256
    auto_tag: true
    file: Dockerfile
    when:
      event: [ push, tag ]

  deploy:
    image: peloton/drone-k8s-deployment
    pull: true
    secrets: [ kubernetes_token, kubernetes_url ]
    namespaces: josmo
    deployment_names: node-sha256
    docker_image: "josmo/node-sha256"
    container_names: node-sha256
    when:
      event: [ tag ]
      branch: [ master ]
